[tool.aerich]
tortoise_orm = "app.db.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.black]
line-length = 80
target-version = ["py311"]

[build-system]
requires = ["black"]
build-backend = "setuptools.build_meta"
